env:
  global:
  - REPO=cvicens/cloudnative-workshop-apb

dist: trusty
sudo: required
language: python
python: "2.7"

services:
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

install:
  - pip install ansible
  - ansible-galaxy install -r apb/requirements-travis.yml
  - ansible-playbook apb/playbooks/provision.yml --syntax-check

script:
  - cd apb
  - docker build -f Dockerfile --label "com.redhat.apb.spec=$(base64 --wrap=0 apb.yml)" -t $REPO:$TRAVIS_COMMIT .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker push $REPO:$TAG